/**
 * One source of truth for everything a crawler reads.
 *
 * Page components never hand-write a title or a meta tag - they call a builder here.
 * That keeps titles inside the pixel budget, keeps descriptions inside the snippet
 * budget, and means a wording change happens in one place.
 */

const rawUrl = import.meta.env?.VITE_SITE_URL ?? 'https://ntaka.com';

export const SITE = {
  name: 'Ntaka',
  url: rawUrl.replace(/\/+$/, ''),
  locale: 'en_GB',
  twitter: '@ntaka',
  /** 1200x630, generated by scripts/build-og-image.sh */
  ogImage: '/og-default.jpg',
  tagline: 'Learn African languages online with native teachers',
  description:
    'Learn Yoruba, Igbo, Hausa, Swahili, Amharic, Zulu and 19 more African languages with native teachers. Live lessons, group classes and interactive courses.',
};

export const absolute = (path = '/') =>
  path.startsWith('http') ? path : `${SITE.url}${path.startsWith('/') ? path : `/${path}`}`;

/* Titles read best under ~60 characters; descriptions under ~155. These clamp rather
   than silently letting a long language name blow the budget. */
const clamp = (text, max) => {
  const clean = String(text).replace(/\s+/g, ' ').trim();
  if (clean.length <= max) return clean;
  // Cut on a word boundary; a snippet ending mid-word looks broken in the SERP.
  const cut = clean.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[\s,;:.\-–—]+$/, '')}…`;
};

export const title = (text) => clamp(text ? `${text} | ${SITE.name}` : `${SITE.name} | ${SITE.tagline}`, 65);
export const description = (text) => clamp(text, 158);

/* --------------------------------------------------------------- page builders */

export const homeSeo = () => ({
  title: `${SITE.name} | ${SITE.tagline}`,
  description: description(SITE.description),
  path: '/',
  keywords: [
    'learn African languages online',
    'Yoruba lessons',
    'Igbo tutor',
    'Hausa classes',
    'Swahili teacher',
    'African language courses',
  ],
});

/**
 * The language pages are the search assets: someone typing "learn Yoruba online" is
 * the exact visitor this platform wants, and this is the page that should meet them.
 */
export const languageSeo = (language) => ({
  title: title(`Learn ${language.name} Online — ${language.teacherCount} Native Teachers`),
  description: description(
    `Learn ${language.name} with ${language.teacherCount} native teachers from ${language.country}. 1-on-1 lessons, live group classes and interactive courses, A1 to C2. Free placement test.`,
  ),
  path: `/languages/${language.id}`,
  keywords: [
    `learn ${language.name}`,
    `${language.name} lessons online`,
    `${language.name} tutor`,
    `${language.name} teacher`,
    `${language.name} classes for beginners`,
    `speak ${language.name}`,
  ],
});

export const teacherSeo = (teacher) => ({
  title: title(`${teacher.name} — Native ${teacher.languageName} Teacher, ${teacher.country}`),
  description: description(
    `Book a 1-on-1 ${teacher.languageName} lesson with ${teacher.name}, a ${teacher.typeLabel.toLowerCase()} from ${teacher.country}. ${teacher.rating ? `Rated ${teacher.rating}/5 from ${teacher.reviews} reviews. ` : ''}Trial lesson from $${teacher.trialPrice}, teaching ${teacher.levels[0]}–${teacher.levels[teacher.levels.length - 1]}.`,
  ),
  path: `/teachers/${teacher.id}`,
});

export const courseSeo = (course) => ({
  title: title(course.title),
  description: description(
    `${course.promise} A self-paced ${course.languageName} course at ${course.level}: ${course.lessonCount} video lessons. ${course.isOpen ? 'Free to read, no account needed.' : 'Included in the Ntaka subscription.'}`,
  ),
  path: `/interactive-learning/${course.id}`,
});

export const classSeo = (item) => ({
  title: title(item.title),
  description: description(
    `Join a live ${item.languageName} ${item.topicLabel.toLowerCase()} at ${item.level}. ${item.durationMins} minutes, ${item.seatsTotal} learners maximum, $${item.pricePerSeat} a seat. ${item.recurrence}${item.teacher ? `, taught by ${item.teacher.name}` : ''}.`,
  ),
  path: `/classes/${item.id}`,
});

export const STATIC_SEO = {
  teachers: {
    title: title('African Language Teachers — Book a 1-on-1 Lesson'),
    description: description(
      'Browse native teachers of Yoruba, Igbo, Hausa, Swahili, Amharic, Zulu and more. Compare ratings, hourly rates and live availability, then book a trial lesson from $3.',
    ),
    path: '/teachers',
  },
  classes: {
    title: title('Live African Language Group Classes Online'),
    description: description(
      'Small live group classes in African languages - conversation clubs, tone labs, proverb circles and business tracks. Four to ten learners, one CEFR level, from $4 a seat.',
    ),
    path: '/classes',
  },
  videoLearning: {
    title: title('Interactive African Language Courses'),
    description: description(
      'On-demand interactive courses in Yoruba, Igbo, Hausa, Swahili and more, recorded by native teachers. One subscription covers every language, with quizzes, certificates and open courses to start free.',
    ),
    path: '/interactive-learning',
  },
  languages: {
    title: title('African Languages You Can Learn Online'),
    description: description(
      '25 African languages across 14 countries, taught by native speakers - from Yoruba, Igbo and Hausa to Swahili, Amharic, Zulu, Twi, Wolof and Darija.',
    ),
    path: '/languages',
  },
  partners: {
    title: title('Partners — Cultural Bodies and Associations'),
    description: description(
      'Ntaka works with cultural ministries, community associations and educators across Africa to teach African languages properly online.',
    ),
    path: '/partners',
  },
  placement: {
    title: title('Free CEFR Placement Test for African Languages'),
    description: description(
      'Free six-minute placement test in Yoruba, Igbo, Hausa, Swahili, Zulu, Twi, Wolof and Amharic. Get your CEFR level, A1 to C2, plus what to study next. No account needed.',
    ),
    path: '/placement-test',
  },
  faq: {
    title: title('Ntaka FAQ — Learning African Languages Online'),
    description: description(
      'Answers on placement tests, 1-on-1 lessons, group classes, interactive courses, pricing, certificates and how your data is handled at Ntaka.',
    ),
    path: '/faq',
  },
  pricing: {
    title: title('Pricing — Lessons, Classes and Subscription'),
    description: description(
      'Private lessons by the hour, group classes priced per person, and every interactive course on one subscription covering all 25 African languages.',
    ),
    path: '/pricing',
  },
  privacy: {
    title: title('Privacy Policy'),
    description: description(
      'How Ntaka collects, uses and protects learner data — including exactly what happens to placement test voice recordings, and every service provider involved.',
    ),
    path: '/privacy',
  },
  terms: {
    title: title('Terms of Service'),
    description: description(
      'The terms for using Ntaka: accounts, the placement test, bookings and cancellations, payments, certificates and teaching on the platform.',
    ),
    path: '/terms',
  },
  cookies: {
    title: title('Cookies and Browser Storage'),
    description: description(
      'Ntaka sets no advertising cookies and no tracking pixels. The complete list of what we store in your browser, and how to clear it.',
    ),
    path: '/cookies',
  },
  notFound: {
    title: title('Page not found'),
    description: description('That page has moved or no longer exists.'),
    path: '/404',
    noindex: true,
  },
};
